### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by JustCallBen** [matthieuheitz/google-data-analyses#1]
First, thank you for writing this.  Second, I really don't want to learn Python; I just want to run the script.  The first error I got was because I didn't have the json data in the same sub as the script. Solved.
The next error was because numpy was not found.  I wanted to install numpy but holy shit, it just ain't easy.

Is there a way to make this more user-friendly?  I have the skills but not the patience.

**Comment by matthieuheitz** [comment]
You should run 'pip install numpy'.
If it still doesn't work, find a tutorial that briefly explains how the
python environment and packages work.
