### ISSUE TITLE
Traceback error - line 73

### ISSUE THREAD

**Issue by nmelin** [matthieuheitz/google-data-analyses#2]
when executing the script, the following traceback message is received

```shell
Traceback (most recent call last):
  File "get_visit_times.py", line 73, in <module>
    accuracy[i] = point['accuracy']
KeyError: 'accuracy'
```

My json file contains `accuracy` keys for all objects. 
Example: `"accuracy" : 30`

The only changes made to the script:

- updated `poi` with my coordinates from google maps
- updated `begin_ts` and `end_ts` with my date range

**Comment by matthieuheitz** [comment]
If there was a KeyError, that must mean that there was an object for which there was no 'accuracy' info.
I fixed the code so that you don't get this error anymore.
