### ISSUE TITLE
Traceback on line 74 in get_visit_times

### ISSUE THREAD

**Issue by alexshurygin** [matthieuheitz/google-data-analyses#4]
Loading 'location_history.json' ...
JSON file loaded
Extracting relevant data...
Traceback (most recent call last):
  File "/home/shurygin/bin/get_visit_times.py", line 74, in <module>
    positions[i] = np.array([float(point['latitudeE7']),float(point['longitudeE7'])])/1e7
KeyError: 'latitudeE7'

**Comment by matthieuheitz** [comment]
Now fixed!
