### ISSUE TITLE
Thanks for your work.

### ISSUE THREAD

**Issue by rnwolf** [matthieuheitz/google-data-analyses#7]
Hi Matthieu

Saw your post on https://webapps.stackexchange.com/questions/102899/can-i-use-googles-timeline-to-get-the-times-ive-been-to-a-specific-location

Wanted to say thanks for https://github.com/matthieuheitz/google-data-analyses/blob/master/get_visit_times.py

Rudi

**Comment by matthieuheitz** [comment]
You're welcome ! Glad you liked it :)
